services:

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: lenny_api
    ports:
      - "8080:80"  
    depends_on:
      - db
      - s3
    env_file: .env
    environment:
      - LENNY_PORT=1337  # When in docker, run Lenny as 1337, reverse proxies from nginx
      - S3_ENDPOINT=s3:9000
    volumes:
      - .:/app
    networks:
      - lenny_network

  db:
    image: postgres:16
    container_name: lenny_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - lenny_network

  s3:
    image: minio/minio:latest
    env_file: .env
    container_name: lenny_bookshelf
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - bookshelf_data:/data
    command: server /data --console-address ":9001"
    networks:
      - lenny_network

  createbuckets:
    image: minio/mc:latest
    env_file: .env  
    container_name: lenny_createbuckets
    depends_on:
      - s3
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    entrypoint: >
      /bin/sh -c "
      for i in $(seq 1 10); do
        mc alias set myminio http://s3:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD && break || sleep 3;
      done;
      mc mb myminio/bookshelf-public 2>/dev/null || true;
      mc anonymous set download myminio/bookshelf-public 2>/dev/null || true;
      mc mb myminio/bookshelf-encrypted 2>/dev/null || true;
      mc anonymous set download myminio/bookshelf-encrypted 2>/dev/null || true;
      exit 0;"
    networks:
      - lenny_network

networks:
  lenny_network:
    driver: bridge

volumes:
  db_data:
  bookshelf_data:
