services:

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: lenny_api
    ports:
      - "8080:80"  # When in docker, run Lenny as 8080, reverse proxies from nginx
    depends_on:
      - db
      - s3
    env_file: lenny.env
    environment:
    - LENNY_PORT=1337  # When in docker, run Lenny as 1337, reverse proxies from nginx
    volumes:
      - ./lenny/migrations:/app/lenny/migrations  # Optional: Mount migrations directory
      - ./Preloaded_books:/app/Preloaded_books # Mount preloaded books
    networks:
      - lenny_network

  db:
    image: postgres:16
    container_name: lenny_db
    restart: always
    env_file: lenny.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - lenny_network

  s3:
    image: minio/minio:latest
    container_name: lenny_bookshelf
    env_file: lenny.env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - bookshelf_data:/data
    command: server /data --console-address ":9001"
    networks:
      - lenny_network

networks:
  lenny_network:
    driver: bridge

volumes:
  db_data:
  bookshelf_data:
