services:

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: lenny_api
    ports:
      - "${LENNY_PORT:-8080}:80"
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_healthy
    env_file: .env
    environment:
      - S3_ENDPOINT=s3:9000
      - DB_HOST=db
      - LENNY_PROXY=${LENNY_PROXY}
    volumes:
      - .:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - lenny_network

  db:
    image: postgres:16
    container_name: lenny_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./readium/db/:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lenny_network

  s3:
    image: minio/minio:latest
    container_name: lenny_s3
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3_data:/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - lenny_network

  reader:
    build:
      context: .
      dockerfile: docker/reader/Dockerfile
    container_name: lenny_reader
    ports:
      - "${READER_PORT:-3000}"
    networks:
      - lenny_network

  readium:
    image: ghcr.io/readium/readium:0.3.0
    container_name: lenny_readium
    ports:
      - "${READIUM_PORT:-15080}"
    depends_on:
      - s3
      - api
    environment:
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
    volumes:
      - readium_data:/srv/publications
    command: >
      serve 
      --file-directory /srv/publications
      --s3-access-key ${S3_ACCESS_KEY}
      --s3-secret-key ${S3_SECRET_KEY}
      --s3-endpoint ${S3_ENDPOINT}
      --s3-use-path-style
      --address 0.0.0.0
      --scheme file
      --scheme s3
      --debug
    networks:
      - lenny_network

  lcpserver:
    build:
      context: ./docker/readium-lcp-server
    container_name: lcpserver
    ports:
      - "8989:8989"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - READIUM_LCPSERVER_CONFIG=/srv/config/config.yaml
    volumes:
      - ./readium/config:/srv/config
      - ./readium/db:/srv/db
      - ./readium/tmp:/srv/tmp
      - ./readium/bookshelf:/bookshelf
    command: ["/usr/local/bin/lcpserver"]
    networks:
      - lenny_network

  lsdserver:
    build:
      context: ./docker/readium-lcp-server
    container_name: lsdserver
    ports:
      - "8990:8990"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - READIUM_LSDSERVER_CONFIG=/srv/config/lsd_config.yaml
    volumes:
      - ./readium/config:/srv/config
      - ./readium/db:/srv/db
      - ./readium/tmp:/srv/tmp
      - ./readium/bookshelf:/bookshelf
    command: ["/usr/local/bin/lsdserver"]
    networks:
      - lenny_network

  lcpencrypt:
    build:
      context: ./docker/readium-lcp-server
    container_name: lcpencrypt
    volumes:
      - ./readium/config:/srv/config
      - ./readium/db:/srv/db
      - ./readium/tmp:/srv/tmp
      - ./readium/bookshelf:/bookshelf
    command: ["tail", "-f", "/dev/null"]
    networks:
      - lenny_network

networks:
  lenny_network:
    driver: bridge

volumes:
  db_data:
  s3_data:
  readium_data:
