services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: lenny_frontend
    ports:
      - "8080:8080"
    volumes:
      - "./lenny/lenny_Front_end:/app/lenny/lenny_Front_end"
    command: sh -c "cd '/app/lenny/lenny_Front_end' && npm install && npm run dev"
    networks:
      - lenny_network
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:7000

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: lenny_backend
    ports:
      - "7001:7000"  # Changed from 7000:7000 to avoid port conflict (nginx api)
      - "7002:7002"  # FastAPI API
      - "5432:5432"  # PostgreSQL
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    volumes:
      - ./lenny/configs/settings.cfg:/app/lenny/configs/settings.cfg:ro
    environment:
      - API_PORT=7000
      - POSTGRES_HOST=localhost
      - MINIO_HOST=localhost
    command: /app/run.sh
    networks:
      - lenny_network

networks:
  lenny_network:
    driver: bridge

volumes:
  db_data:
  minio_data: