"""add unlogged cache table

Revision ID: f132daa4029f
Revises: 001_baseline
Create Date: 2026-03-28 13:50:01.133285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f132daa4029f'
down_revision: Union[str, None] = '001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    prefixes=['UNLOGGED']
    )
    op.create_index('idx_cache_expires', 'cache', ['expires_at'], unique=False)
    op.create_index('idx_cache_scope_key_expires', 'cache', ['scope', 'key', 'expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cache_scope_key_expires', table_name='cache')
    op.drop_index('idx_cache_expires', table_name='cache')
    op.drop_table('cache')
    # ### end Alembic commands ###
