public_base_url: http://localhost:8081
port: 8081
dsn: ""

access:
  username:
  password: 

license:
  provider: "http://lennyforlibrarians.org"
  profile: "http://readium.org/lcp/basic-profile"
  hint_link: "http://lennyforlibrarians.org/help/lcp/{license_id}"

status:
  renew_default_days: 30
  renew_max_days: 365
  renew_link: "http://lennyforlibrarians.org/renew/{license_id}"

certificate:
  cert: "/app/cert/cert-edrlab-test.pem"
  private_key: "/app/cert/privkey-edrlab-test.pem"
